### ISSUE TITLE
Is the "Pin board desktop: Src" duplicated

### ISSUE THREAD

**Issue by hbaileylxd** [chris-steele/adapt-ppq#2]
I have to add the image twice, with exactly the same wording in the schema.

Has this been duplicated by error? Or maybe the second is for mobile? If so the distinction isn't clear.

**Comment by chris-steele** [comment]
@hmaffin this is intentional: there is `_pinboardDesktop` and `_pinboardMobile` for the two device types - usually these will take the same values, though the flexibility exists in cases, for example, when there is a particularly detailed image for desktop that requires a more simplified version for mobile.
